# id: 1
server:
  address: "server:12345"
loop:
  amount: 5
  period: "5s"
log:
  level: "INFO"
batch:
  maxAmount: 150 # Considering that a bet has around 55 bytes and the max size of a batch is 8KB

